#!/bin/bash

cmd_path="$(realpath $0)"
srcdir_root="$(dirname "$(dirname "$cmd_path")")"

java -classpath "$srcdir_root/lib/cbc.jar" \
     c.compiler.Compiler \
     -I"$srcdir_root" \
	 --dump-tokens \
     "$@"
